version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    # Add healthcheck to ensure Ollama is ready
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Add model initialization service
  ollama-init:
    image: ollama/ollama:latest
    entrypoint: ["ollama"]
    command: ["pull", "qwen2.5-coder:7b"]
    volumes:
      - ollama_data:/root/.ollama
    depends_on:
      ollama:
        condition: service_healthy

  bespoke-code:
    build: .
    volumes:
      - ./workspace:/app/workspace
    environment:
      - OLLAMA_HOST=ollama
      - WORKSPACE_DIR=/app/workspace
    depends_on:
      ollama-init:
        condition: service_completed_successfully

volumes:
  ollama_data: 