# API Configuration
OLLAMA_URL = "http://localhost:11434/api/generate"

# Token Management
QWEN_MAX_TOKENS = 32768
SYSTEM_RESERVED_TOKENS = 4000
QUERY_RESERVED_TOKENS = 2000
MAX_HISTORY_TOKENS = QWEN_MAX_TOKENS - SYSTEM_RESERVED_TOKENS - QUERY_RESERVED_TOKENS

# Model Configuration
DEFAULT_TEMPERATURE = 0.7
DEFAULT_MAX_TOKENS = 2000 